### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by gangLi2022** [wgcban/ddpm-cd#35]
Refer to your code，when train diffusion ,Running the code gives an error in the  " diffusion = Model.create_model(opt)" ,debug the error ,the unet has mistake,some mistakes takes as below:
:Traceback (most recent call last):
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\fs_image.py", line 80, in <module>
    diffusion = Model.create_model(opt)
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\__init__.py", line 7, in create_model
    m = M(opt)
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\model.py", line 18, in __init__
    self.netG = self.set_device(networks.define_G(opt))
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\network.py", line 98, in define_G
    image_size=model_opt['diffusion']['image_size']
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\ddpm_modules\unet.py", line 208, in __init__
    dropout=dropout, with_attn=use_attn))
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\ddpm_modules\unet.py", line 151, in __init__
    dim, dim_out, noise_level_emb_dim, norm_groups=norm_groups, dropout=dropout)
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\ddpm_modules\unet.py", line 101, in __init__
    self.block1 = Block(dim, dim_out, groups=norm_groups,dropout=dropout)
  File "F:\Diffusion model-based semantic segmentation for polarization imaging\model\ddpm_modules\unet.py", line 85, in __init__
    nn.GroupNorm(groups, dim),
  File "D:\Anaconda\envs\diffusion_model_semantic\lib\site-packages\torch\nn\modules\normalization.py", line 251, in __init__
    if num_channels % num_groups != 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'

**Comment by wgcban** [comment]
@gangLi2022 I have fixed this issue rn. Thanks for pointing out.
