### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for GaussianDiffusion:

### ISSUE THREAD

**Issue by cxh1028** [wgcban/ddpm-cd#45]
Excuse me，I have the following problem, can you help me solve it.
Traceback (most recent call last):
  File "ddpm_cd.py", line 88, in <module>
    diffusion = Model.create_model(opt)
  File "F:\anaconda\envs\xxxpytorch\lib\site-packages\torch\nn\modules\module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GaussianDiffusion:
        Unexpected key(s) in state_dict: "denoise_fn.downs.12.attn.norm.weight", "denoise_fn.downs.12.attn.norm.bias", "denoise_fn.downs.12.attn.qkv.weight", "denoise_fn.downs.12.attn.out.weight", "denoise_fn.downs.12.attn.out.bias", "denoise_fn.downs.13.attn.norm.weight", "denoise_fn.downs.13.attn.norm.bias", "denoise_fn.downs.13.attn.qkv.weight", "denoise_fn.downs.13.attn.out.weight", "denoise_fn.downs.13.attn.out.bias", "denoise_fn.ups.0.attn.norm.weight", "denoise_fn.ups.0.attn.norm.bias", "denoise_fn.ups.0.attn.qkv.weight", "denoise_fn.ups.0.attn.out.weight", "denoise_fn.ups.0.attn.out.bias", "denoise_fn.ups.1.attn.norm.weight", "denoise_fn.ups.1.attn.norm.bias", "denoise_fn.ups.1.attn.qkv.weight", "denoise_fn.ups.1.attn.out.weight", "denoise_fn.ups.1.attn.out.bias", "denoise_fn.ups.2.attn.norm.weight", "denoise_fn.ups.2.attn.norm.bias", "denoise_fn.ups.2.attn.qkv.weight", "denoise_fn.ups.2.attn.out.weight", "denoise_fn.ups.2.attn.out.bias".

**Comment by 15216257736** [comment]
I'm also running into this issue, please did you solve it with English translation?

**Comment by yxzz1121** [comment]
Me too，how to solve it
